<?php $this->widget('bootstrap.widgets.TbExtendedGridView', array(
    'type'=>'striped bordered condensed',
    'id'=>'taxones-grid',
    'dataProvider'=>$listTaxones,
    'ajaxUrl'=>array('taxon/busqueda'),
	'columns'=>array(
    	array( 'name'=>'id', 'header'=> 'Id'),
    	array( 'name'=>'name', 'header'=> 'Taxón'),
    	array( 'name'=>'kingdom', 'header'=> 'Reino'),
		array( 'name'=>'phylum', 'header'=> 'Phylum'),
    	array( 'name'=>'class', 'header'=> 'Clase'),
    	array( 'name'=>'order', 'header'=> 'Orden'),
		array( 'name'=>'family', 'header'=> 'Familia'),
		array( 'name'=>'genus', 'header'=> 'Género'),
    	array( 'name'=>'epitetoes', 'header'=> 'Epíteto Específico'),
    	array( 'name'=>'epitetoin', 'header'=> 'Epíteto Infraespecífico'),
    	array( 'name'=>'rank', 'header'=> 'Rango'),
    	array( 'name'=>'author', 'header'=> 'Autor'),
    	array( 'name'=>'specie', 'header'=> 'Nombre Científico'),
    	array( 'name'=>'specieid', 'header'=> 'LSID'),
	),
)); ?>